### ISSUE TITLE
Unable to run the demos locally 

### ISSUE THREAD

**Issue by shivaylamba** [webmachinelearning/webnn-samples#112]
I tested running the sample examples locally but the following errors are coming both in MacOS and in Windows : 
1. Local VS Code Console Error : 
![image](https://user-images.githubusercontent.com/19529592/144272182-cdc4f74e-2444-4bcd-939f-9bf49e1d224c.png)

2. Browser Error : 
![image](https://user-images.githubusercontent.com/19529592/144272274-a554f4f6-cea8-4725-a2de-7768a8c4df61.png)

Both of them are for the missing kernels. Do we have to download the weights separately for each of the projects?

**Comment by shivaylamba** [comment]
@Honry

**Comment by shivaylamba** [comment]
@Honry I just realized that the test-data is on another repository. So can we make edit in the ReadME to mention this during the setup process that to get the test-data you would need to install it from the test-data repository otherwise if we just clone this repository, the test-data folder is empty. I can work on this particular issue if you want.

**Comment by Honry** [comment]
Thanks @shivaylamba, actually the `test-data` is the submodule of `webnn-samples`, therefore we required cloning `webnn-samples` with `--recurse-submodules` option in README.md.

`git clone --recurse-submodules https://github.com/webmachinelearning/webnn-samples`

it'd be great if you'd like to contribute to webnn-samples, we may need to make it clear on how/why we use `test-data` in README.md.

**Comment by shivaylamba** [comment]
Alright thanks a lot Honry. I would definitely like to contribute for the same.
