### ISSUE TITLE
Fast style transfer error

### ISSUE THREAD

**Issue by dirkk0** [webmachinelearning/webnn-samples#118]
Hi!
Thanks for making this available!

I get an error on the fast style transfer example saying:
"the value length 874800 is invalid, size of [1,3,33,33] 3267 is expected." and it never starts. This is on Chrome (also Canary) and Firefox, Mac OSX and POP_OS.

In the console it also shows: "Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'" but this may be unrelated.

Thanks,
  Dirk

**Comment by Honry** [comment]
Sorry this issue was out of track. I just check the latest sample, the issue you mentioned has gone, while another issue occurs on WebGL backend due to https://github.com/webmachinelearning/webnn-polyfill/issues/174. Wasm backend works fine.

**Comment by BruceDai** [comment]
@Honry https://github.com/webmachinelearning/webnn-polyfill/issues/174 was fixed. Currently, I run Fast style transfer sample by Wasm and WebGL backend successfully.

**Comment by Honry** [comment]
Thanks @BruceDai!

@dirkk0, please try the latest [sample](https://webmachinelearning.github.io/webnn-samples/style_transfer/index.html), it should work now. I'm closing this issue and please let me know if you have further question.
