### ISSUE TITLE
Integrate the code editor into the spec doc

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn-samples#13]
In [2020/10/01 WebML CG call](https://www.w3.org/2020/10/01-webmachinelearning-minutes.html#t02), @pyu10055 suggested 

> <ping_yu> It would be good to integrate this (code examples) with the spec doc

**Comment by huningxin** [comment]
The code editor was added into the [explainer](https://github.com/webmachinelearning/webnn/blob/master/explainer.md). I am not sure whether we can close this issue? @anssiko @pyu10055

**Comment by anssiko** [comment]
I think this addresses the issue, thanks!
