### ISSUE TITLE
Need Face detection and Face Recognition samples migrated to new Framework as old ones crashing in Live camera use case

### ISSUE THREAD

**Issue by roshansullad** [webmachinelearning/webnn-samples#143]
Hi,

I am looking for Face detection and recognition samples migrated to new repository, but i don't see any specific samples there, and i tried samples from old repository ([[https://github.com/intel/webml-polyfill [github.com]](https://github.com/intel/webml-polyfill%20%5bgithub.com%5d)) but those are crashing in the live camera case. we are looking for latest libraries which support FR/FD functionality to use in our project. so anything available immediately is of great help. 

Regards
Roshan

**Comment by Honry** [comment]
@roshansullad we just add following samples as you requested: 
* [Facial Landmark Detection](https://webmachinelearning.github.io/webnn-samples/facial_landmark_detection/index.html)
* [Face Recognition](https://webmachinelearning.github.io/webnn-samples/face_recognition/index.html)

Please try and let us know if you have any question.

**Comment by roshansullad** [comment]
Sure Honry,

Thanks for doing it so quickly, will let you know if any issues we face. 

Thank you very much
