### ISSUE TITLE
Update some samples using static paddings

### ISSUE THREAD

**Issue by BruceDai** [webmachinelearning/webnn-samples#166]
~- [ ] Image classification (ResNet50v2 NHWC model)~
- [x] Fast style transfer

Refer to latest Spec change https://github.com/webmachinelearning/webnn/pull/355

**Comment by Honry** [comment]
@BruceDai, actually only fast style transfer use `pad` now.

**Comment by Honry** [comment]
For style transfer, fixed in https://github.com/webmachinelearning/webnn-samples/pull/167, PTAL, thanks!

**Comment by BruceDai** [comment]
Yes, https://github.com/webmachinelearning/webnn-samples/pull/162 has already merge pad into conv2d, so no need to fix the first item. And I reviewed #167, LGTM.
