### ISSUE TITLE
Inconsistent ”Could not get context for WebGL version 2” error message

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn-samples#21]
Steps to reproduce:

1. Load https://webmachinelearning.github.io/webnn-samples/code/?example=mul_add.js

2. Click Run
3. Console log prints:

```
Could not get context for WebGL version 2
Output shape: 2,2
Output value: 1,1,1,1
```
4. Click Run again
5. Console log prints:

```
Output shape: 2,2
Output value: 1,1,1,1
```

Expected log messages in 3 and 5 to be identical, including the WebGL error message.

Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1

**Comment by huningxin** [comment]
I think "Could not get context for WebGL version 2" is reported by tf.js. Ping @pyu10055 , am I correct? 

Probably we could filter it out from logging.

**Comment by anssiko** [comment]
I was able to reproduce the issue with https://js.tensorflow.org/api/latest/#add so I opened https://github.com/tensorflow/tfjs/issues/4284

I think it is better to address this issue in the upstream, so I'm closing this issue.

**Comment by gauravdhra** [comment]
chrome browser is  unable to draw canvas .showing same error 
`Could not get context for WebGL version 2`


![image](https://user-images.githubusercontent.com/40135431/105951120-90c2a100-6095-11eb-8f50-9ea299e02eac.png)

**Comment by anssiko** [comment]
(Just a reminder this bug is tracked upstream: https://github.com/tensorflow/tfjs/issues/4284)
