### ISSUE TITLE
Add the style transfer example

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn-samples#25]
https://github.com/webmachinelearning/webnn/issues/108

**Comment by Honry** [comment]
We're considering using newer models, @huningxin, @BruceDai, following's the comparison list of FNS Candy Style Transfer from different orgs, PTAL which is more appropriate for this example.

Fast Neural Style Transfer | Candy | Candy | Candy
-- | -- | -- | --
Org | [ONNX model zoo](https://github.com/onnx/models/tree/master/vision/style_transfer/fast_neural_style) | [ONNX model zoo](https://github.com/onnx/models/tree/master/vision/style_transfer/fast_neural_style) | [microsoft/Windows-Machine-Learning](https://github.com/microsoft/Windows-Machine-Learning/tree/master/Samples/FNSCandyStyleTransfer/UWP/cs/Assets)
OpSet Version | 8 | 9 | N/A
Input | float32[1,3,224,224] | float32[1,3,224,224] | float32[None,3,720,720]
Missing Ops in Spec | Upsample | Shape,   Gather, Cast, Unsqueeze, Upsample | Crop,   Affine
uploaded time | 10 months ago | 10 months ago | 3   years ago
Size | 6.6M | 6.6M | 1.64M


Note:   ONNX Upsample is replaced with Resize.

BTW, one more dependency is that some existing ops on Spec have not been implemented in webnn-polyfill yet. Relevant issue: https://github.com/webmachinelearning/webnn-polyfill/issues/34

**Comment by Honry** [comment]
After discussion, we decide to use [ONNX model zoo](https://github.com/onnx/models/tree/master/vision/style_transfer/fast_neural_style)'s style transfer models with opSet version 9.

**Comment by huningxin** [comment]
Thanks @Honry for your investigation and looking forward to your code contribution. 

@anssiko , I added Wanming as collaborator so Wanming can be assignee of this issue.

**Comment by anssiko** [comment]
@Honry thanks for looking into these new models, your contributions are much welcome.

**Comment by huningxin** [comment]
> Missing Ops in Spec	Upsample

Unsample/Resize can be mapped to [`resample`](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-resample) op.

**Comment by huningxin** [comment]
When testing the fast style transfer [model](https://github.com/onnx/models/tree/master/vision/style_transfer/fast_neural_style) of ONNX model zoo, there are couple of issues of webnn-polyfill/tf.js:

- For WebGL backend, the last conv2d with input [1, 32, 904, 904] and filter [3, 32, 9, 9] would hit the WebGL maximum texture size restriction:

```
uncaught (in promise) Error: Requested texture size [22808x22809] greater than WebGL maximum on this browser / GPU [16384x16384].
```

- For Wasm backend, the `tf.mirrorPad` and `tf.image.resizeNearestNeighbor` are not supported.

**Comment by Honry** [comment]
@huningxin, with [Acer models](https://github.com/acerwebai/VangoghCrazyWorld), I still got error for WebGL backend:

> uncaught (in promise) Error: Requested texture size [19467x19468] greater than WebGL maximum on this browser / GPU [16384x16384].

**Comment by Honry** [comment]
> @huningxin, with [Acer models](https://github.com/acerwebai/VangoghCrazyWorld), I still got error for WebGL backend:
> 
> > uncaught (in promise) Error: Requested texture size [19467x19468] greater than WebGL maximum on this browser / GPU [16384x16384].

Sorry, it's my bad, there's a typo in my code, it works now.
