### ISSUE TITLE
[NNotepad] deleting text doesn't cause refresh

### ISSUE THREAD

**Issue by inexorabletash** [webmachinelearning/webnn-samples#255]
Repro:

1. Load https://webmachinelearning.github.io/webnn-samples/nnotepad/index.html
1, In text field, select everything after `a = 123`, press backspace/delete

Expected:

* results area updates with scalar 123

Actual:

* results area still shows 2 tensors (result of `split()` example)

Notes:

* The code adds an `"input"`event listener to the `#input` element, which calls `refresh()`. The Monaco editor must not be firing this for deletion events? Is there a better way to listen to the Monaco editor?

**Comment by inexorabletash** [comment]
@ibelem maybe you have some ideas?

**Comment by ibelem** [comment]
@inexorabletash Thanks for reporting this issue, I'm sorry for bringing such regression. Real-time response to changes will be more convenient for developers. Please help to review the fix in https://github.com/webmachinelearning/webnn-samples/pull/257 , thanks!
