### ISSUE TITLE
Can not enable NPU surpport in Chrome Canary

### ISSUE THREAD

**Issue by akau16** [webmachinelearning/webnn-samples#272]
I run WebNN on NPU in Edge Dev is OK, but in Chrome Canary is not OK by WebNN Installation Guides' steps, thoses sample's NPU button is still disable, anybody have same problems?

Chrome version: 130.0.6700.0 canary
directML version: 1.15.2
NPU: Intel AI Boost Driver Version: 32.0.100.2540

Thank You!

**Comment by huningxin** [comment]
May I know what is the error message you got?

The installation guide has been updated including steps for Chrome Canary: https://github.com/webmachinelearning/webnn-samples?tab=readme-ov-file#running-webnn-on-npu

At the current stage, devs need to copy the DirectML.dll to Chrome Canary's version folder. 

> Note that Chrome Canary frequently updates automatically. When this occurs, you'll need to recopy the DirectML.dll to the new version's directory
