### ISSUE TITLE
Face recognition example does not work locally on latest Chrome Canary: `Invalid signature.`

### ISSUE THREAD

**Issue by jaanli** [webmachinelearning/webnn-samples#282]
Hi! This is a really cool project and I am rewriting https://github.com/prouast/heartbeat-js using the face recognition example.

However, when getting started with the code at https://github.com/webmachinelearning/webnn-samples/blob/master/face_recognition/ - I ran into the following bug: 

<img width="1195" alt="image" src="https://github.com/user-attachments/assets/cc3e538f-6fa6-4a65-b7ab-4e2f1cf5c828">

Specifically, `Invalid signature.` displays at the top of Chrome Canary.

Steps I followed:

- forked the repository
- git clone
- npm install to install vite dependencies
- `npm run start`

Then navigate to https://localhost:5173/ in Chrome Canary, and receive the error.

Any help on debugging this to enable remote vital signs monitoring with WebNN? Thank you!

**Comment by Honry** [comment]
@jaanli, WebNN-Samples requires to access to  weight files located at [test-data](https://github.com/webmachinelearning/test-data) which is a submodule of this repo.
I suppose you forgot download the test-data to local,
```
git clone --recurse-submodules https://github.com/webmachinelearning/webnn-samples
```

**Comment by jaanli** [comment]
That solved it, thanks so much @Honry !!
