### ISSUE TITLE
[Gemm] only support 2d tensor

### ISSUE THREAD

**Issue by fujunwei** [webmachinelearning/webnn-samples#47]
The bias is 1D tensor that isn't supported in WebNN, please reshape it to 2D like [native implementation](https://github.com/otcshare/webnn-native/blob/main/examples/MobileNetV2/MobileNetV2.cpp#L121)

https://github.com/webmachinelearning/webnn-samples/blob/master/image_classification/mobilenet_nchw.js#L44
`const bias = await buildConstantByNpy(this.builder_, biasName);`

**Comment by huningxin** [comment]
The 1D bias is fixed by webnn spec. Could we close this issue? @fujunwei

**Comment by fujunwei** [comment]
Yes, close it.
