### ISSUE TITLE
Deployment fails due to PR #45 merge

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn-samples#50]
https://github.com/webmachinelearning/webnn-samples/actions/runs/873331801

@Honry , please help fix this issue. Thanks!

**Comment by Honry** [comment]
@mingmingtasd 's PR https://github.com/webmachinelearning/webnn-samples/pull/49/ will fix this issue. I've reviewed it and please help merge if you have no more comments. @huningxin  :)

**Comment by Honry** [comment]
Fixed in #49, close it.
