### ISSUE TITLE
Add the semantic segmentation sample

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn-samples#53]
This sample would be according to WebNN [semantic segmentation use case](https://webmachinelearning.github.io/webnn/#usecase-segmentation).

**Comment by Honry** [comment]
@huningxin, which models should we support?

**Comment by huningxin** [comment]
Both [DeepLabV3](https://webmachinelearning.github.io/webnn/#biblio-deeplabv3) and [MaskR-CNN](https://webmachinelearning.github.io/webnn/#biblio-maskr-cnn) are referenced in the spec. They would be good ones for start.

@pyu10055 @wchao1115, any recommendations?
