### ISSUE TITLE
hi i want to use webnn for noise supression in my application. could someone guide me how to start and any sample code or anything helpfull 

### ISSUE THREAD

**Issue by vishaldhull09** [webmachinelearning/webnn-samples#81]

**Comment by vishaldhull09** [comment]
Hi @Honry 
is the dataset on which this model is trained public ?
could you please provide me the link to dataset

**Comment by Honry** [comment]
Hi @vishaldhull09, yes, it's public, you can get dataset of NSNet2 from https://github.com/microsoft/DNS-Challenge.

**Comment by miaobin** [comment]
Hi @vishaldhull09 , we have implemented a real-time [sample](https://github.com/miaobin/webnn-samples/tree/rnnoise-real-time/audio_stream) of noise suppression (RNNoise) based on mediacapture-transform API. This sample successfully constructed a pipeline to suppress the noise of the audio data collected by the microphone and send it to the speaker or earphone of the device.
I think this example will solve your question and we will close this issue. If you have any questions, please feel free to contact us.

**Comment by Honry** [comment]
Thanks @miaobin! I will close this issue.
