### ISSUE TITLE
Add the RNNoise example

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn-samples#9]
The RNNoise is one of [the first wave models](https://github.com/webmachinelearning/webnn/blob/master/op_compatibility/first_wave_models.md).

**Comment by huningxin** [comment]
@miaobin , please help on this example. Thanks!

**Comment by miaobin** [comment]
[PR](https://github.com/webmachinelearning/webnn-samples/pull/69) merged.

**Comment by Honry** [comment]
Thanks @miaobin! Close it.
